FROM python:3.9-slim

WORKDIR /app

# Install system dependencies (needed for LightGBM)
RUN apt-get update && apt-get install -y \
    libgomp1 \
     && rm -rf /var/lib/apt/lists/*
     
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
     
COPY . .
     
EXPOSE 7860

CMD ["streamlit", "run", "app.py", "--server.port=7860", "--server.address=0.0.0.0"]